name: Créer un tag de version

on:
  workflow_dispatch:
    inputs:
      increment_type:
        description: "Type de version (major, minor, patch)"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Copie du repo
        uses: actions/checkout@v5

      - name: "Création de tag"
        id: tag
        uses: chancie86/github-action-version-tag@v0.0.1-pre.25
        with:
          versionPrefix: "v"
          incrementType: ${{ github.event.inputs.increment_type == 'major' && 'Major' || github.event.inputs.increment_type == 'minor' && 'Minor' || "Patch" }}
          push: true

      - name: Afficher la nouvelle version
        run: |
          echo "Version actuelle : ${{ steps.tag.outputs.currentVersion }}"
          echo "Nouvelle version : ${{ steps.tag.outputs.nextVersion }}"
